name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
          
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
        
      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: ./gradlew test --continue

      # - name: Report
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: Maven Tests
      #     path: '**/build/test-results/TEST-*.xml'
      #     reporter: java-junit
      #     fail-on-error: true

      - name: Upload coverage for matrix module
        uses: actions/upload-artifact@v2
        with:
          name: test-case reports
          path: build/github
